version: '3.9'

services:

  front:
    image: sermalenk/skypro-front:lesson-34
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
      collect_static:
        condition: service_completed_successfully
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static/



  collect_static:
    image: ${DOCKERHUB_USER}/todolist:latest
    env_file: .env
    command: python manage.py collectstatic -c --no-input
    volumes:
      - ./django_static:/app/static/

  api:
    image: ${DOCKERHUB_USER}/todolist:latest
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    image: ${DOCKERHUB_USER}/todolist:latest
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    command: python -m manage migrate

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 10s
      retries: 10
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  django_static: