# Generated by Django 4.2.3 on 2023-07-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='added',
            field=models.DateField(auto_now_add=True, verbose_name='Date_added'),
        ),
    ]
