# Generated by Django 4.2.3 on 2023-07-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='added',
        ),
    ]
