# Generated by Django 4.2.3 on 2023-07-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_birth_day_alter_user_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
