# Generated by Django 4.2.3 on 2023-07-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
